name: Gh-Pages-Staging

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v3
